version: '3'
services:
  auth-server:
    build: ./auth-server
    ports:
      - "5000:5000"
  resource-server:
    build: ./resource-server
    ports:
      - "5001:5001"
  client:
    build: ./client
    ports:
      - "3000:3000"
